\version "2.24.0"

tempoKyrie = \tempoMarkup "Allegro"
tempoGloria = \tempoMarkup "Andante"
tempoCredo = \tempoMarkup "Allegro"
  tempoEtIncarnatus = \tempoMarkup "Adagio"
  tempoEtResurrexit = \tempoMarkup "Allegro"
tempoSanctus = \tempoMarkup "Adagio"
  tempoPleni = \tempoMarkup "Allegro"
tempoBenedictus = \tempoMarkup "Andante"
  tempoOsanna = \tempoMarkup "[Allegro]"
tempoAgnus = \tempoMarkup "Adagio"
  tempoDona = \tempoMarkup "Allegro"

\include "notes/chords.ly"
\include "notes/org.ly"
