\version "2.24.0"

tempoJesu = \tempoMarkup ""
tempoEs = \tempoMarkup ""
tempoUnter = \tempoMarkup ""
tempoDenn = \tempoMarkup ""
tempoTrotz = \tempoMarkup ""
tempoIhr = \tempoMarkup ""
  tempoIhrB = \tempoMarkup "Adagio"
tempoWeg = \tempoMarkup ""
tempoSoAber = \tempoMarkup "Andante"
tempoGute = \tempoMarkup ""
tempoSoNun = \tempoMarkup ""
tempoWeicht = \tempoMarkup ""

\include "notes/chords.ly"
\include "notes/org.ly"
